export const dummy = {
  dates: { maximum: "2024-01-17", minimum: "2023-12-06" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      genre_ids: [36, 10752, 18],
      id: 753342,
      original_language: "en",
      original_title: "Napoleon",
      overview:
        "프랑스군 지휘관이었던 나폴레옹의 기원과 빠르고 냉혹하게 황제 자리에 오르게 된 이야기를 아내이자 유일한 참사랑이었던 조세핀과 맺었던 중독적이고 불안정한 관계를 통해 가까이서 들여다본다.",
      popularity: 2998.164,
      poster_path: "/cFOpMbj28ZKhXDy50mrIcLhLb8g.jpg",
      release_date: "2023-12-06",
      title: "나폴레옹",
      video: false,
      vote_average: 6.463,
      vote_count: 1123,
    },
    {
      adult: false,
      backdrop_path: "/iNgn9LP0iMuLSnWqolivcY3Y7F6.jpg",
      genre_ids: [28, 12, 14],
      id: 572802,
      original_language: "en",
      original_title: "Aquaman and the Lost Kingdom",
      overview:
        "아틀란티스 왕국을 이끌 왕의 자리에 오른 아쿠아맨. 그 앞에 블랙 만타가 세상을 뒤흔들 강력한 지배 아이템 블랙 트라이던트를 손에 넣게 된다. 그동안 겪지 못 했던 최악의 위협 속 아쿠아맨은 블랙 만타와 손을 잡았던 이복 동생 옴 없이는 절대적 힘이 부족한 상황. 바다를 지배할 슈퍼 히어로가 세상의 판도를 바꾼다!",
      popularity: 1393.421,
      poster_path: "/eDps1ZhI8IOlbEC7nFg6eTk4jnb.jpg",
      release_date: "2023-12-20",
      title: "아쿠아맨과 로스트 킹덤",
      video: false,
      vote_average: 6.471,
      vote_count: 486,
    },
    {
      adult: false,
      backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
      genre_ids: [16, 10751, 10402, 14, 35],
      id: 901362,
      original_language: "en",
      original_title: "Trolls Band Together",
      overview:
        "전 세계 모든 트롤을 열광케 했던 최고의 아이돌 그룹 ‘브로존’. 역대급 무대 실수와 형제 간의 불화로 결국 해체한 뒤, 모두에게 잊혀 간다. 그러던 어느 날, ‘브로존’의 황금막내 ‘브랜치’는 메인보컬 ‘플로이드’가 슈퍼스타 ‘벨벳’과 ‘비니어’에게 잡혀 재능을 빼앗기고 있다는 소식을 듣는다. 그를 구하기 위해서는 흩어져 있는 ‘브로존’을 재결합하고 완벽한 화음을 되찾아야 하는데… 12월, 가장 짜릿한 컴백 무대의 시작!",
      popularity: 759.154,
      poster_path: "/qzgEPduJyQ6RkgMdn4nbjdKUYJM.jpg",
      release_date: "2023-12-20",
      title: "트롤: 밴드 투게더",
      video: false,
      vote_average: 7.2,
      vote_count: 524,
    },
    {
      adult: false,
      backdrop_path: "/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "가족을 과잉보호하는 아빠 ‘맥’ 때문에 평생을 작은 연못에서 안전하게 살아온 말러드 가족. 하지만 호기심 가득한 남매 ‘댁스’와 ‘그웬’을 위해 새로운 세상을 모험하고 싶은 엄마 ‘팸’의 설득으로 가족들은 항상 꿈꿔온 자메이카로 생애 첫 가족 모험을 떠나기로 한다! 설렘 넘치는 시작과 달리 태풍을 만나 길을 잃고, 낯선 친구들을 만나고, 위험 가득한 뉴욕에 불시착하게 된다. 인생 처음으로 모든 계획이 틀어지고 위기에 빠진 말러드 가족은 서툴지만 서로를 의지하며 모험을 계속한다. 새로운 세상, 함께라면 두려울 것 없어!",
      popularity: 424.548,
      poster_path: "/2xE3NI6zElWhwN9WJ92fqbZKmzZ.jpg",
      release_date: "2024-01-10",
      title: "인투 더 월드",
      video: false,
      vote_average: 7.453,
      vote_count: 106,
    },
    {
      adult: false,
      backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      genre_ids: [16, 10751, 14, 12],
      id: 1022796,
      original_language: "en",
      original_title: "Wish",
      overview:
        "마음 속 깊이 ‘소원’을 품고 있는 모두를 위한 디즈니의 마법! 용감한 ‘아샤’와 신비로운 ‘별’의 특별한 여정 \u0026 소원과 얽힌 비밀스러운 힘을 지닌 ‘매그니피코 왕’의 숨겨진 스토리까지! 2024년 1월, 믿고 듣는 디즈니표 명품 OST와 함께 아름다운 로사스 왕국에서 펼쳐지는 가슴 벅찬 이야기!",
      popularity: 348.534,
      poster_path: "/lnOgP8Fl2dQ73d4Qu24O2zcKFFS.jpg",
      release_date: "2024-01-03",
      title: "위시",
      video: false,
      vote_average: 6.338,
      vote_count: 272,
    },
    {
      adult: false,
      backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
      genre_ids: [27, 53, 9648],
      id: 951491,
      original_language: "en",
      original_title: "Saw X",
      overview:
        "존은 암을 치료할 수 있는 기적을 기대하며 위험하고 실험적인 의료 시술을 받기 위해 멕시코로 떠났지만, 이 모든 수술이 가장 취약한 사람들을 속이기 위한 사기라는 사실을 알게 된다",
      popularity: 265.257,
      poster_path: "/bvwEkotIuHxjuSCEXhhSna0BqQT.jpg",
      release_date: "2023-12-13",
      title: "쏘우 X",
      video: false,
      vote_average: 7.369,
      vote_count: 1412,
    },
    {
      adult: false,
      backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
      genre_ids: [28, 53, 80],
      id: 762430,
      original_language: "en",
      original_title: "Retribution",
      overview:
        "대규모 자금을 운용하는 펀드 매니저 ‘매트’(리암 니슨)에게 걸려온 한 통의 미확인 발신자 전화!  그의 요구는 2억 8천만 유로를 송금할 것, 전화를 끊거나 차를 멈추지 말 것!",
      popularity: 249.419,
      poster_path: "/jJNgvme2a51MRCJoE7dL4Vpzv8Z.jpg",
      release_date: "2023-12-06",
      title: "레트리뷰션",
      video: false,
      vote_average: 6.89,
      vote_count: 825,
    },
    {
      adult: false,
      backdrop_path: "/9ZlGiEKmcYrrxmiQEJDhjeT2kEW.jpg",
      genre_ids: [28, 12, 10752],
      id: 1061181,
      original_language: "ja",
      original_title: "キングダム 運命の炎",
      overview:
        "천하대장군을 꿈꾸는 소년 ‘신’, 조나라가 10만 대군을 이끌고 진나라에 침공을 강행하자 보병대로 전쟁에 출전한다. 진나라가 요충지까지 함락당하며 멸망의 위기에 놓인 그때, ‘신’은 전설의 천하대장군 ‘왕기’에게 100인 부대의 대장으로 임명되어 특수한 임무를 하달받는다. 단 100명의 비신대를 이끌고 적진에 침투하라! ‘신’과 동료들은 목숨을 건 운명의 전투를 시작하는데…!",
      popularity: 182.17,
      poster_path: "/60eYZkkksgKeeAV8fAAKQslZZnH.jpg",
      release_date: "2024-01-17",
      title: "킹덤3: 운명의 불꽃",
      video: false,
      vote_average: 7.612,
      vote_count: 89,
    },
    {
      adult: false,
      backdrop_path: "/et0G74BxoBgNQEZBkUcVhsgeRFF.jpg",
      genre_ids: [18, 10749, 10402],
      id: 523607,
      original_language: "en",
      original_title: "Maestro",
      overview:
        "음악의 전설 레너드 번스타인과 펠리시아 몬테알레그레 콘 번스타인. 평생에 걸친 두 사람의 복잡한 관계를 따라가는 거침없는 사랑 이야기.",
      popularity: 82.197,
      poster_path: "/moiFIJn0vplfmucUDntyj4c11T.jpg",
      release_date: "2023-12-06",
      title: "마에스트로 번스타인",
      video: false,
      vote_average: 6.466,
      vote_count: 305,
    },
    {
      adult: false,
      backdrop_path: "/kZbTOcTrEGyroQMWQSGIRlNSkwP.jpg",
      genre_ids: [878, 28, 14, 12],
      id: 626412,
      original_language: "ko",
      original_title: "외계+인 2부",
      overview:
        "인간의 뇌 속에 갇혀 있는 외계인 포로들의 탈출을 막으려다 먼 과거에 갇혀버린 이안과 썬더는 시간을 관통하는 문을 열 수 있는 신검을 얻게 된다. 한편, 이안의 탈출을 도왔던 무륵은 자신의 몸에 이상한 존재가 있다는 것을 느끼자 혼란에 빠진다. 무륵의 몸에 숨어있는 외계인으로 의심되는 존재가 이안과 무륵을 추격하기 시작하고, 이안은 미래로 돌아가 외계인과 맞서 하바의 폭발을 막아야만 하는데.  마침내 시간의 문이 열리고 무륵, 이안, 썬더의 비밀이 드러나기 시작한다!",
      popularity: 78.578,
      poster_path: "/hBxVes0oK7uoNwAQ2meJ2LVthPI.jpg",
      release_date: "2024-01-10",
      title: "외계+인 2부",
      video: false,
      vote_average: 8.3,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/bQTfSXQrcVwXJ5TvNzbd3ioMnnM.jpg",
      genre_ids: [9648, 53, 28, 18],
      id: 862552,
      original_language: "en",
      original_title: "The Ritual Killer",
      overview:
        "강력계 형사 루카스 보이드는 딸과 아내의 죽음으로 괴로워하며 하루하루를 살아간다. 그러던 중 매우 기괴하고 잔인한 수법의 살인사건이 발생한다. 사건현장을 둘러보고 평범한 살인사건이 아니라고 판단한 루카스는 아프리카 문화의 권위자로 꼽히는 맥클스 교수를 찾아가 도움을 청한다. 루카스는 범인이 고객의 의뢰를 받고 무티라는 의식을 거행하기 위해 피해자들을 제물로 사용한다는 사실을 알아내고 맥클스 교수의 도움으로 남아공 출신의 흑주술사 랜도쿠를 뒤쫓는다. 한편 거대 다국적 기업의 대표인 파너의 의뢰를 받고 일하는 랜도쿠는 또 다른 범행을 꾸미는데... 과연 루카스 형사는 잔인한 살인마이자 흑주술사인 랜도쿠를 막을 수 있을까?",
      popularity: 75.15,
      poster_path: "/ivfflZulJY4qtHcsAZ7P94ygJ15.jpg",
      release_date: "2024-01-17",
      title: "무티: 주술 살인",
      video: false,
      vote_average: 6.056,
      vote_count: 223,
    },
    {
      adult: false,
      backdrop_path: "/ec1yA7FoHltRHxxFS7cBvOarbvc.jpg",
      genre_ids: [9648, 27, 53],
      id: 1160003,
      original_language: "en",
      original_title: "Night of the Hunted",
      overview:
        "오늘밤, 보이지 않는 총구가 당신을 노린다! 한밤중 외딴 편의점에 들른 앨리스는 갑자기 총에 맞고 쓰러진다. 누가 어디서 무슨 이유로 쏘는지 알 수 없지만, 탈출을 시도할 때마다 정확히 날아오는 총알! 도움도, 구조도 없다! 밀실 아닌 밀실이 된 이곳에서 반드시 탈출하라!",
      popularity: 28.368,
      poster_path: "/8d0hLEl2JZyeE4mCgyNSz6hbnee.jpg",
      release_date: "2023-12-06",
      title: "노 엑시트",
      video: false,
      vote_average: 6.736,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: "/hb0BeFvZNx2zLGWwuwENOIVeK1U.jpg",
      genre_ids: [35, 18, 36],
      id: 792293,
      original_language: "en",
      original_title: "Dumb Money",
      overview:
        "“주식 시장에서 이렇게 황당한 일은 처음 봐요!” “상승세가 멈추질 않는데요?” 월 스트리트를 제대로 물 먹인 개미들의 짜릿한 떡상 실화 스토리가 시작된다!",
      popularity: 46.65,
      poster_path: "/hSJl0U8Wi1YVORKI0hIbiXt1xSL.jpg",
      release_date: "2024-01-17",
      title: "덤 머니",
      video: false,
      vote_average: 6.735,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: "/oQMcTqUkz1LIQceyjyiA4UO9UgM.jpg",
      genre_ids: [35, 18, 10749],
      id: 986280,
      original_language: "fi",
      original_title: "Kuolleet lehdet",
      overview:
        "2024년, 헬싱키의 외로운 두 영혼 안사와 홀라파는 어느 날 우연히 만나 눈길을 주고받는다. “그럼 또 만날까요? 근데 이름도 모르네요” “다음에 알려줄게요” 서로의 이름도, 주소도 알지 못한 채 유일하게 받아 적은 전화번호마저 잃어버린다. 운명이 이들을 갈라놓으려 할 때 두 사람은 다시 만날 수 있을까?",
      popularity: 33.756,
      poster_path: "/3D3w06xQtFcFEFuYuv9D6m93fJM.jpg",
      release_date: "2023-12-20",
      title: "사랑은 낙엽을 타고",
      video: false,
      vote_average: 7.223,
      vote_count: 173,
    },
    {
      adult: false,
      backdrop_path: "/bW2R6PejAFk6FVCyLmTsgn8ETqZ.jpg",
      genre_ids: [28, 878],
      id: 634429,
      original_language: "ja",
      original_title: "シン・ウルトラマン",
      overview:
        "일본 전역에서 정체불명의 괴수가 잇따라 출현하자 정부는 이들을 ‘화위수’라 명명하고 대응팀 ‘화특대’를 신설한다. ‘화위수’에 의한 국가적 위기가 임박해진 와중, 돌연 은빛의 거인이 나타나 ‘화위수’를 퇴치한다. 거인의 정체를 알아내기 위해 투입된 분석관 ‘아사미’는 그것에 ‘울트라맨’이라는 이름을 붙인다. 며칠 후, 이번에는 외성인에 의해 다시 위기에 빠진 ‘화특대’. 그 때, 어디선가 ‘울트라맨’이 나타나 ‘화특대’ 기지를 파괴하고 그를 아군이라 생각했던 인간들은 혼란에 빠지는데…",
      popularity: 37.45,
      poster_path: "/kyIFa7jROnKEGY6R6XXWTNOzu5E.jpg",
      release_date: "2023-12-06",
      title: "신 울트라맨",
      video: false,
      vote_average: 7.1,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: "/AfyuI3glMCBDFmNPj9PY6DwbgGp.jpg",
      genre_ids: [16, 878, 28, 18],
      id: 18491,
      original_language: "ja",
      original_title: "新世紀エヴァンゲリオン劇場版 Air／まごころを、君に",
      overview:
        "‘카오루’의 죽음 이후 공황 상태에 빠진 ‘신지’. 한편, 네르프 총사령관 ‘겐도’는 ‘서드 임팩트’ 즉, ‘인류보완계획’을 놓고 ‘제레’와 갈등을 벌인다. 이에 ‘제레’는 양산형 에바를 투입해 네르프 본부와 에바 파일럿들을 향해 총공격을 감행하고 맹공에 혼수 상태였던 ‘아스카’까지 완전히 폭주한다. ‘신지’는 ‘미사토’의 도움으로 겨우 초호기에 오르지만, 인류의 운명을 결정해야 하는 상황에 한계에 부딪히게 되는데…",
      popularity: 40.198,
      poster_path: "/rS97sHvlsUAp8F6tkC78YjRU8wl.jpg",
      release_date: "2024-01-17",
      title: "엔드 오브 에반게리온",
      video: false,
      vote_average: 8.3,
      vote_count: 1433,
    },
    {
      adult: false,
      backdrop_path: "/oeBom7DLr85lixEkWOGmhCPEfuY.jpg",
      genre_ids: [80, 18, 53],
      id: 842942,
      original_language: "en",
      original_title: "Bandit",
      overview:
        "1985년, 미시간 교도소에서 탈옥해 캐나다로 건너간 한 남자. 노숙자에게 22달러에 신분증을 구매해 ‘로버트 화이트만’으로 새로운 삶을 시작하고, 돈을 마련하기 위해 은행 강도에 나선다. 변장과 은행털이에 남다른 재능을 발견한 그는 비행기를 타고 캐나다 전역을 누비며 무려 59번의 강도 행각을 벌이는데…",
      popularity: 37.251,
      poster_path: "/a8v0tN3D0sFwBH2YVuQRpzhUE0i.jpg",
      release_date: "2023-12-28",
      title: "밴디트",
      video: false,
      vote_average: 6.177,
      vote_count: 260,
    },
    {
      adult: false,
      backdrop_path: "/H8YE8DDrnvr869RgCqLvhfcUFM.jpg",
      genre_ids: [18],
      id: 970348,
      original_language: "en",
      original_title: "The Old Oak",
      overview:
        "영국의 북동쪽에 위치한 한 마을, 예전엔 광산의 광부들로 활기찼던 마을이었지만 폐광 이후로 떠나지 못한 일부 주민들만이 마을을 지키며 살고 있다. 빈집이 늘어남에 따라 마을의 집값은 떨어지기만 하고 주민들의 불만은 고조되어 가는 어느 날, 영국 정부에서 허가한 시리아 난민들이 마을로 집단 이주를 하게 된다. 가뜩이나 먹고살기 힘든 주민들과 시리아 난민들 사이에 눈에 보이지 않은 묘한 긴장감이 흐르는 와중에, 한 시리아 여성과 마을에서 유일한 술집을 운영하는 한 남자의 우정이 싹트기 시작한다.",
      popularity: 29.558,
      poster_path: "/74ZjRIFRblBHMz9SBqHjR3XJaoi.jpg",
      release_date: "2024-01-17",
      title: "나의 올드 오크",
      video: false,
      vote_average: 7.4,
      vote_count: 146,
    },
  ],
  total_pages: 4,
  total_results: 76,
};
